version: '3.8'
services:
  db:
      container_name: pg_container
      image: postgres
      restart: always
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      ports:
        - "5432:5432"
      volumes:
        - $HOME/Desktop/PostgreSql-Snippets/infile:/infile
        - pg_data:/var/lib/postgresql/data/
volumes:
  pg_data: